# Default values for application-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fluent-bit:
  podSecurityPolicy:
    create: false
  config:
    service: |
      [SERVICE]
          Daemon Off
          Flush 1
          Log_Level info
          Parsers_File parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port 2020
          Health_Check On
    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/*.log
          multiline.parser docker, cri
          Tag kube.*
          Mem_Buf_Limit 5MB
          Skip_Long_Lines On
    filters: |
      [FILTER]
          Name kubernetes
          Match kube.*
          Merge_Log On
          Keep_Log Off
          K8S-Logging.Parser On
          K8S-Logging.Exclude On

      [FILTER]
          Name rewrite_tag
          Match kube.var.log.containers.fluent*
          Rule $log .* drop false

      [FILTER]
          Name rewrite_tag
          Match kube.var.log.containers.otel*
          Rule $log .* drop false

      [FILTER]
          Name rewrite_tag
          Match kube.var.log.containers.application-operator*
          Rule $log .* drop false

      [FILTER]
          Name rewrite_tag
          Match kube.var.log.containers.application-api*
          Rule $log .* drop false


    outputs: |
      [OUTPUT]
          Name null
          Match drop

      [OUTPUT]
          Name http
          Match *_{{ .Release.Namespace }}_*
          Host application-api
          Uri logs/
          Format json_lines
