version: 2.1
orbs:
  skedulo: skedulo/ci@0.5.3

parameters:
  image:
    default: skedulo/application-operator
    type: string

jobs:
  test:
    docker:
      - image: cimg/python:3.8.6

    steps:
      - setup_remote_docker:
          docker_layer_caching: true
          version: 19.03.14
      - checkout
      - run:
          name: Install submodule
          command: git submodule update --init

      - run:
          name: Run python static analysis checks
          command: |
            pip install flake8
            flake8

workflows:
  everything:
    jobs:
      - test
      - skedulo/build_and_push_image:
          name: build_image_<<matrix.executor>>
          context:
            - aws-ecr
            - prisma
          matrix:
            parameters:
              executor:
                - skedulo/amd64
                - skedulo/arm64
          image: <<pipeline.parameters.image>>
          push: false
          use_buildkit: true
          filters:
            branches:
              ignore:
                - main
          requires:
            - test

      - skedulo/build_and_push_image:
          name: build_and_push_image_<<matrix.executor>>
          context:
            - aws-ecr
            - prisma
          matrix:
            alias: build_and_push_image
            parameters:
              executor:
                - skedulo/amd64
                - skedulo/arm64
          image: <<pipeline.parameters.image>>
          use_buildkit: true
          filters:
            branches:
              only:
                - main
          requires:
            - test

      - skedulo/create_and_push_manifest:
          name: create_and_push_manifest
          context: aws-ecr
          images: <<pipeline.parameters.image>>:${VERSION_TAG}-amd64,<<pipeline.parameters.image>>:${VERSION_TAG}-arm64
          manifest: <<pipeline.parameters.image>>
          requires:
            - build_and_push_image
