apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "application-operator.serviceAccountName" . }}
  namespace: {{ .Release.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "application-operator.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "application-operator.serviceAccountName" . }}
  namespace: {{ .Release.namespace }}
