apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applications.application-operator.github.io
spec:
  group: application-operator.github.io
  names:
    kind: Application
    listKind: ApplicationList
    plural: applications
    singular: application
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Application is the Schema for the applications API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ApplicationSpec defines the desired state of Application
            properties:
              application:
                maxLength: 24
                type: string
              environment:
                maxLength: 10
                type: string
              method:
                type: string
              version:
                type: string
            required:
            - application
            - environment
            - version
            type: object
          status:
            description: ApplicationStatus defines the observed state of Application
            properties:
              configVersion:
                type: string
              lastUpdated:
                format: date-time
                type: string
            required:
            - configVersion
            - lastUpdated
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
