apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-operator
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      name: application-operator
  template:
    metadata:
      labels:
        name: application-operator
    spec:
      serviceAccountName: application-operator
      containers:
        - name: application-operator
          # Replace this with the built image name
          image: quay.io/skedulo/application-operator:v0.0.0
          command:
          - application-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "application-operator"
