kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: application-operator
subjects:
- kind: ServiceAccount
  name: application-operator-executor
roleRef:
  kind: Role
  name: application-operator-executor
  apiGroup: rbac.authorization.k8s.io
