apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "application-api.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "application-api.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "application-api.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
