apiVersion: v2
name: application-operator
description: A Helm chart for Kubernetes

type: application
version: 0.1.0

dependencies:
- name: fluent-bit
  repository: https://fluent.github.io/helm-charts
  version: "0.20.9"
- name: fluentd
  repository: https://fluent.github.io/helm-charts
  version: "0.3.9"
