name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: RyanSiu1995/kubebuilder-action@v1.2
      with:
        version: 3.1.0

    - name: Test
      run: make test
